project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!activity_templates/"
  resources:
    - "data/*.csv"

website:
  title: "STAT/COMP 212"
  navbar:
    background: primary
    search: true
    left:
      - file: index.qmd
        text: "Home"
      - file: schedule.qmd
        text: "Schedule"
      - sidebar:syllabus
      - sidebar:activities
      - sidebar:homework
      - file: project.qmd
        text: "Project"
      - file: tech_setup.qmd
        text: "Tech Setup"

  sidebar:
    - id: syllabus
      title: "Syallbus"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - syllabus_final.qmd
        - syllabus_prelim.qmd
      
    - id: activities
      title: "Activities"
      contents:
        - 01-introductions.qmd
        - 02-adv-ggplot.qmd
        - 03-adv-maps.qmd
        - workflow_files_rstudio.qmd
        - 04-interactive-viz.qmd
        # - 05-data-types.qmd
        # - 06-functions-control-structs.qmd

    - id: homework
      title: "Homework"
      contents:
        - homework0.qmd
        - homework1.qmd
        - homework2.qmd
        - homework3.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    code-overflow: wrap

editor: source

page-footer:
  left: |
    &copy; Leslie Myint, 2023<br>
    All content licensed under ![](https://static.thenounproject.com/png/70967-200.png){height=20px} ([CC BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/))
  right: |
    Site built with [Quarto](https://quarto.org/)
