---
title: "Homework 0"
subtitle: "Your values and 10-year vision"
sidebar: false
---

::: {.callout-tip title="A note from your instructor"}
When I started college, the main thinking I did about my capital-F Future (that nebulous thing way out in the distance) was about what I would be doing after college. It made me very anxious.

Through the many years since my college experience, I have come to see that what allows me to be more at peace with my capital-F Future *now* is a deeper understanding of *who I am* and *what my values are*.

I want to give you a chance to do this kind of thinking now with this "assignment".
:::

I invite you to write an essay (tentatively) titled "My past, present and future and the values they express". (Change the title if you wish!)

**This essay does not need to be submitted and is not due at any point.** If you ever wish to talk to me about what you wrote, the process of writing it, or what you've thought about after writing it, I'd love to do that over a walk or a cup of hot chocolate.

I do hope that by writing it you are able to move forward with your college experience this semester with more peace and clarity. For that reason alone, I *suggest* that you write this essay by the end of the first week of class (Sunday, September 10).

It might be helpful to do/think about the following as you write:

1. Visit this [Values Exercise page](https://www.think2perform.com/values/) to read a very short bit about core values and their role in a fulfilling life. Click the "Start the Exercise" button to complete a ~15 minute exercise to identify your core values.

2. What events brought you to Macalester, and what core values do you think led you to choose Mac?

3. Where do you see yourself in 10 years? How do you see yourself living? What would it take to get to that point? To think through that process in steps, think about:
    - 10-year vision (what's going on in 2033 and why?)
    - 5-year vision (what's going on in 2028 and why?)
    - 2-year vision (what's going on in 2025 and why?)
    - 1-year vision (what's going on in 2024 and why?)
    - 6-month vision (what's going on in Spring 2024 and why?)
    - Thinking about the "why" for these visions can help affirm and clarify the core values you ended up with from the Values Exercise above. For example, if part of your 5-year vision wasn't happening, how would you feel and why?

If it helps at all to look at someone else's vision as you craft your own, I tried to write [my own 10-year vision](https://lesliemyint.substack.com/p/my-10-year-telescope) earlier this summer.




