---
title: "STAT/COMP 212: Intermediate Data Science (Fall 2023)"
sidebar: false
---

This is the course website for STAT/COMP 212: Intermediate Data Science at Macalester College for the Fall 2023 semester taught by Professor [Leslie Myint](https://www.lesliemyint.org). Materials were developed by Leslie Myint and [Brianna Heggeseth](https://bcheggeseth.github.io/).

# Drop-in (office) hours

- **Where?** OLRI 232
- **When?**
    - Mondays: 11-noon and 3:30-4:30
    - Fridays: 3:30-4:30

I'm also happy to meet one-on-one if my normal drop-in hours don't work. You can schedule a time to meet with me via [Calendly](https://calendly.com/lmyint).

# Announcements

## 10/3

- [Project Milestone 2](project.qmd#milestone-2) can be turned in this Wednesday 10/4 or next Wednesday 10/11
- [Reflection 1](reflection1.qmd) is due next Wednesday 10/11. (I'm still finishing writing out the prompts--I'll send a Moodle message later today when it's ready.)
- Check out our [Schedule](schedule.qmd).
    - On Thursday we'll talk about writing functions.
    - Next week we'll talk about loops and iteration.
    - Make note of <span class="project">Project progress presentations</span> on 10/24 and 11/16.

## 9/28

- I thought we might be able to cover wrangling factors today, but we'll save that for next Tuesday.
- Look at the updated [Schedule page](schedule.qmd). The readings there are excellent references and can be read before or after class on Tuesday.

## 9/26

- If you haven't already found an initial dataset, peruse the [Tidy Tuesday](https://github.com/rfordatascience/tidytuesday) repository for ideas.
    - [Homework 4](homework4.qmd) (due next Wednesday 10/4) is to complete [Project Milestone 2](project.qmd#milestone-2).
- Thursday topics: wrangling strings (with regular expressions) and factors
- In place of a standard Homework 5, we will have the first of 3 substantive reflections.

## 9/19

- On Thursday:
    - We will spend the first 30 moving our course projects moving forward.
    - In the last hour of class, facilitators will come in to run an activity for the Classroom Community and Connectedness Survey. (I will be leaving.) A reminder of why this activity is important to me from our [syllabus](syllabus_final.qmd#community-is-key):
    - "A sense of [community](https://www.educause.edu/research-and-publications/books/learning-spaces/chapter-4-community-hidden-context-learning) and connectedness can provide a powerful environment for learning: **Research shows that learning is maximized when students feel a sense of belonging in the educational environment (e.g., Booker, 2016). A negative climate may create barriers to learning, while a positive climate can energize students' learning** (e.g., Pascarella & Terenzini, cited in How Learning Works, 2012)."

## 9/14

- Before next Tuesday's class
    - Check the Schedule page. There is a short podcast segment (~7 min) to listen to and one guiding question to answer. This podcast segment shares a bit of wisdom about when it is/isn't useful to make fancy visualizations.
    - Install the `shiny` and `plotly` packages. Post on the `#questions` channel on Slack if you run into problems. (Share your commands and error messages.)

- Next Thursday we will be having facilitators come in for the last hour of class for the Classroom Community and Connectedness Survey. (I will be leaving.)
    - We will use the first 30 to get our course projects moving forward.

## 9/12

- Homework 1 due Wednesday at midnight (Finishing up the temperature + precipitation plots from last Tuesday)
    - Updated submission instructions can be found [here](02-adv-ggplot.qmd#homework). (Also in the most recent Moodle announcement.)
- Homework 2 due next Wednesday, 9/20 has two parts:
    - Finish Open-ended Exercise from today's [Advanced Map Visualization](03-adv-maps.qmd#open-ended-exercise-homework) activity.
    - Complete Milestone 1 of the [course project](project.qmd)
- There is a [final version of our syllabus](syllabus_final.qmd) that incorporates the learning goals and grading option that we discussed on our first day.

## 9/7

- I'll be adding a new version of the syllabus to our course website that incorporates our final choice for grading system and the learning goals that you contributed.
- Complete the [pre-course survey](https://docs.google.com/forms/d/e/1FAIpQLSc1_48NE_5LxRJ5R5EDPoEWcX4d1-Kyicclbn9EjoFiv8ZW5w/viewform?usp=sf_link) by 3pm today to shape when I hold drop-in hours (office hours).
- Look at the updated Schedule page. We have Guiding Questions for next Tuesday's class: advanced map visualization.
    - Note that Guiding Questions never have to be turned in. Do answer them to the best of your ability before class. We'll spend time at the start of class checking in on these.

## 9/5

To do before class on Thursday:

- Set up R and RStudio using [these instructions](tech_setup.qmd).
- [Join](https://join.slack.com/t/statcomp212fall2023/shared_invite/zt-22hwq73vn-IOFifr_VpO_4AAN4vYVDgA) our Slack workspace.
    - Update your Slack profile with preferred name, pronouns, name pronunciation. (To find your profile, click on your name under Direct Messages on the left menu, and click "Edit Profile".)
    - Introduce yourself in the `#general` channel.
- Complete the [pre-course survey](https://docs.google.com/forms/d/e/1FAIpQLSc1_48NE_5LxRJ5R5EDPoEWcX4d1-Kyicclbn9EjoFiv8ZW5w/viewform?usp=sf_link).
- Look at the [Guiding Questions](schedule.qmd#guiding-questions) for Thursday's class on advanced ggplot2.
- Take a look at [Homework 0](homework0.qmd).
    - This is a personal essay that doesn't need to be turned in.
    - Topic: Your 10-year vision
    - My hope is that writing this allows gives you more clarity on how to align what you do this semester (and beyond) with who/what/how you want to be.
- Finish writing your 12 favorite problems and post them in the `#12-favorite-problems` channel on Slack.
    - When you connect with peers from Thursday onward, you'll be using your 12FPs to get to know each other a bit first before working on activities together.
