---
title: "Project"
sidebar: false
---

# Goal

The goal of the project is to **build something awesome** that you can showcase on your digital portfolio (your personal website).


<br><br>


# Project requirements

**Team size:** You will be working on this project over the course of the semester in teams of 2 or 3.

**Aligning with other classes:** You may choose a project topic that is the same or similar to a topic that you're exploring in another course. This is encouraged! Combining multiple course perspectives can significantly increase the quality of your work.

**Other requirements:** The only requirement for your project is that it addresses your research questions. I do *not* have requirements that, for example, your project uses Shiny, maps, or a particular source of data.

As detailed in the Milestones below, your project *does* need to address 3 research questions. These questions may not be the ones you outlined in Milestone 1. Through iterating on your initial investigations, you may find that your questions change. That's fine.

**Deliverables:**

- A final project presentation
- You will create a Quarto webpage to showcase your project that could be hosted on your personal website if you wish


<br><br>


# Project milestones

## Milestone 1

Identify a data context that interests you. (Your 12 favorite problems might serve as a good source of inspiration.) Identify 3 different data sources that relate to that context. Think beyond a spreadsheet; the most interesting projects may involve collecting and aggregating data from multiple sources and formats. We might not have covered all of the tools needed to acquire that data at this point, so check in with the instructor about the sources that you've found to make sure that they're workable.

- Example non-spreadsheet data sources: search results on a webpage, text of an article, Tweets, other social media posts.

Brainstorm 3 questions about your data context and sources that pique your curiosity.

Due date: Wednesday, 9/20 as part of HW2.



## Milestone 2

- Form project teams.
- Finalize one initial data source and questions related to that source.
- Each team member should create 1 "ugly" (not fully polished) visualization to demonstrate viability of the research questions. (Think of this as visualization "prototyping".)

Due date: Wednesday, 10/11 as part of HW4. (You can submit early on 10/4 if you'd like.)



## Milestone 3

Perform the data acquisition, wrangling, visualization, and modeling needed to address **one** of your research questions. Note that your question might not be amenable to modeling (or to modeling that you've learned about so far). For that reason, modeling is not required, but visualization is.

**Deliverable:** Project progress presentation #1--to be presented in class on Tuesday 10/24.

- **How long?** Prepare a 5-7 minute presentation.

- **What should be in your presentation?**
    - An introduction to your project domain/focus: What questions are you hoping to answer? What question are you focusing on right now? Why is this important to you?
    - An introduction to your data sources
    - Who is impacted (whether positive or negatively) by your analysis? How are you addressing this?
    - Present a few polished visualizations and interpretations that address your current research question

- **Why am I asking you to do this?**
    - Organizing your work for a short presentation is a good way to stay on track and guarantee some useful intermediate work
    - Based on the Classroom Community and Connectedness survey results, there was a desire for more authentic collaboration. I feel that this type of class activity is fertile ground for true collaboration.

- **What feedback will you receive?**
    - Based on the context you present, the instructor and your classmates will give feedback on any suggestions for ethical considerations in your analysis.
    - We will also give feedback on the clarity of your visualizations and your interpretations of them.



## Milestone 4

Adjust data sources and research questions as needed based on the results of explorations so far. Perform the data acquisition, wrangling, visualization, and modeling needed to address another one of your research questions.

**Deliverable:** Project progress presentation #2 on **Tuesday, 11/21**. Instead of presenting to the class, you will present to 1-2 other groups for feedback.

- **How long?** Prepare a 10 minute presentation. *Please practice and keep to this time limit to be mindful of the limited time we have together.*

- **What should be in your presentation?**
    - You should tell a cohesive data story that:
        - Clearly motivates why you have chosen to explore this topic and the particular questions that you investigated
        - Clearly discusses what you found with attention to limitations and cautions arising from ethical considerations and data limitations
        - Discusses what future work is planned in the remainder of the project

- **Why am I asking you to do this?**
    - At this point in your project work, it's important to try to tie together all of your findings into a cohesive story. Presenting to your peers who are not familiar with your context is a great source of feedback in ensuring that your presentation is accessible to a general audience.

- **What feedback will you receive?**
    - Your peers will give you feedback on the clarity and organization of your data story.
        - Did the presenters provide enough context for the "why?" behind their topic?
        - Is it clear what research questions/goals are being pursued?
        - Were concerns regarding ethics and data limitations addressed well?
        - Does the future work seem reasonable?


<br><br>


# Final presentation

Finalize your investigations and the format that you want your final product to take. Possible formats include:

- Blog post
- Standalone Shiny app (e.g., dashboard style with an `app.R` file)
- Blog post with Shiny features (In RStudio, when you choose File > New File > Quarto Document, you can choose the "Interactive" option to generate this format.)

On the last day of class, you will give an **8-10 minute** presentation. *Please practice and keep to this time limit. In order to get through all groups and have time for questions, we need to keep to this time frame.*

You don't necessarily need to have slides for this final presentation if your project format ends up being something like a Shiny app.

**What should be in your presentation?** Your communication goal should be to tell a cohesive data story that:

- Clearly and briefly motivates why you have chosen to explore this topic and the particular questions that you investigated.
    - Given that groups have already presented intermediate results earlier in the semester, this part of the presentation can be more concise than it was in the first presentation.
- Discusses key takeaways from your investigations
- Clearly discusses what you found with attention to limitations and cautions arising from ethical considerations and data limitations

**Presentation order:** Groups will go in the order listed in [this document](https://docs.google.com/document/d/1BwgKdFXdWeaOiaDB-OGRcBhXM36qTIo79BmYZ9hvxko/edit?usp=sharing).


<br><br>


# Moodle submission and assessment

**By midnight on Wednesday, 12/13:** Please submit [on Moodle](https://moodle.macalester.edu/mod/assign/view.php?id=52279) all code files associated with your project. If you made slides for your final presentation or if you have hosted your project on the web, please also submit a URL to those slides or to your hosted project.

**Assessment:** Based on the work that I have seen everyone do over the course of the semester, I am very proud of all projects, so I don't want you to be worried about any harsh evaluation on my end in terms of letter grades. As part of [Reflection 3](reflection3.qmd), you will reflect on your learning via the project, and I will respond based on what I observe based on your final presentation and your submitted code.



